name: Build

on:
  workflow_call:
  push:

jobs:
  windows-aarch64:
    name: windows aarch64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake .. -A ARM64 -DDOTNET_DIR=C:\Program Files\dotnet
          cmake --build . --config Release
      - uses: actions/upload-artifact@v4
        with:
          name: netcoredbg-win-arm64
          path: |
            build/src/Release/netcoredbg.exe
            build/src/Release/dbgshim.dll
            build/src/Release/ManagedPart.dll
            build/src/Release/Microsoft.CodeAnalysis.CSharp.Scripting.dll
            build/src/Release/Microsoft.CodeAnalysis.CSharp.dll
            build/src/Release/Microsoft.CodeAnalysis.Scripting.dll
            build/src/Release/Microsoft.CodeAnalysis.dll
