name: Build

on:
  workflow_call:
  push:

jobs:
  windows-aarch64:
    name: windows aarch64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Find .NET SDK path
        shell: pwsh
        run: |
          dotnet --info
          $dotnetRoot = (Get-Command dotnet).Source | Split-Path
          echo "DOTNET_DIR=$dotnetRoot" >> $env:GITHUB_ENV
          echo "Dotnet root: $dotnetRoot"
          ls $dotnetRoot
      - name: Build
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake .. -A ARM64 -DDOTNET_DIR="%DOTNET_DIR%"
          cmake --build . --config Release
      - uses: actions/upload-artifact@v4
        with:
          name: netcoredbg-win-arm64
          path: |
            build/src/Release/netcoredbg.exe
            build/src/Release/dbgshim.dll
            build/src/Release/ManagedPart.dll
            build/src/Release/Microsoft.CodeAnalysis.CSharp.Scripting.dll
            build/src/Release/Microsoft.CodeAnalysis.CSharp.dll
            build/src/Release/Microsoft.CodeAnalysis.Scripting.dll
            build/src/Release/Microsoft.CodeAnalysis.dll
